---
- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  roles:
    - common

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - k3s/master

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - k3s/node
